[build][build]

  command = "pnpm install && pnpm build"  command = "pnpm install && pnpm build"

  publish = "dist"  publish = "dist"

  functions = "netlify/functions"

[[redirects]]

[functions]  from = "/*"

  node_bundler = "esbuild"  to = "/index.html"

  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
