// Auto-generated by upload-icons-to-appwrite.ts
// تم إنشاؤه تلقائياً بواسطة سكريبت رفع الأيقونات

export const appwriteAssets = {
  endpoint: 'https://cloud.appwrite.io/v1',
  projectId: '68d8b9db00134c41e7c8',
  bucketId: 'public-assets',
  
  // روابط مباشرة للأصول
  icons: {
    'favicon-16x16.png': 'https://cloud.appwrite.io/v1/storage/buckets/public-assets/files/favicon-16x16.png/view?project=68d8b9db00134c41e7c8',
    'favicon-32x32.png': 'https://cloud.appwrite.io/v1/storage/buckets/public-assets/files/favicon-32x32.png/view?project=68d8b9db00134c41e7c8',
    'favicon-48x48.png': 'https://cloud.appwrite.io/v1/storage/buckets/public-assets/files/favicon-48x48.png/view?project=68d8b9db00134c41e7c8',
    'apple-touch-icon.png': 'https://cloud.appwrite.io/v1/storage/buckets/public-assets/files/apple-touch-icon.png/view?project=68d8b9db00134c41e7c8',
    'android-chrome-192x192.png': 'https://cloud.appwrite.io/v1/storage/buckets/public-assets/files/android-chrome-192x192.png/view?project=68d8b9db00134c41e7c8',
    'android-chrome-512x512.png': 'https://cloud.appwrite.io/v1/storage/buckets/public-assets/files/android-chrome-512x512.png/view?project=68d8b9db00134c41e7c8',
    'og-image.jpg': 'https://cloud.appwrite.io/v1/storage/buckets/public-assets/files/og-image.jpg/view?project=68d8b9db00134c41e7c8',
    'logo.png': 'https://cloud.appwrite.io/v1/storage/buckets/public-assets/files/logo.png/view?project=68d8b9db00134c41e7c8',
    'logo-dark.png': 'https://cloud.appwrite.io/v1/storage/buckets/public-assets/files/logo-dark.png/view?project=68d8b9db00134c41e7c8',
    'manifest.json': 'https://cloud.appwrite.io/v1/storage/buckets/public-assets/files/manifest.json/view?project=68d8b9db00134c41e7c8'
  },
  
  // دالة مساعدة للحصول على URL أي أصل
  getAssetUrl(filename: string): string {
    return `${this.endpoint}/storage/buckets/${this.bucketId}/files/${filename}/view?project=${this.projectId}`;
  }
};
